language: go

go: "1.14"

install:
- wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
- sudo apt install unzip
- sudo unzip ninja-linux.zip -d /usr/local/bin/
- go get -u github.com/roman-mazur/bood/cmd/bood

script:
- cd build/
- bood
- mv -f build-copy.bood build.bood
- ./out/bin/bood
- cat ./out/reports/bood_test/test.txt