language: go

go: "1.14"

install:
- wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
- sudo unzip ninja-linux.zip
- mv ninja $GOPATH/bin

script:
- cd $GOPATH/src/github.com/KPI-Labs/design-lab-2/build
- sudo chmod +x init-bood
- ./init-bood
- ./out/bin/bood 